from .core import (
    AnnotationStrategy,
    NLPTask,
    BUDGET_LEVELS,
    ExperimentConfig,
    LearningCurvePoint,
    LearningCurve,
    CostModel,
    UncertaintySamplingMetrics,
    fit_learning_curve,
    predict_f1,
)
from .evaluate import (
    pareto_frontier,
    area_under_learning_curve,
    cost_to_target_f1,
    strategy_comparison,
    budget_recommendation,
    cost_efficiency_curve,
    annotation_roi,
)
from .data import STRATEGY_F1_CURVES, make_learning_curve, make_full_dataset
from .structured import (
    NERDataset,
    NERExample,
    QADataset,
    QAExample,
    RelationExtractionDataset,
    RelationExtractionExample,
    SummarizationDataset,
    SummarizationExample,
)
from .structured_metrics import (
    bio_tags_to_spans,
    entity_level_f1,
    mean_rouge_l_f1,
    qa_exact_match,
    qa_scores,
    qa_token_f1,
    relation_macro_f1,
    rouge_l_f1,
)
from .metrics import calibration_score, expected_calibration_error, lari_score
from .taxonomy import FailureCategory, FailureCode, summarize_failure_codes

__all__ = [
    "AnnotationStrategy",
    "NLPTask",
    "BUDGET_LEVELS",
    "ExperimentConfig",
    "LearningCurvePoint",
    "LearningCurve",
    "CostModel",
    "UncertaintySamplingMetrics",
    "fit_learning_curve",
    "predict_f1",
    "pareto_frontier",
    "area_under_learning_curve",
    "cost_to_target_f1",
    "strategy_comparison",
    "budget_recommendation",
    "cost_efficiency_curve",
    "annotation_roi",
    "STRATEGY_F1_CURVES",
    "make_learning_curve",
    "make_full_dataset",
    "NERDataset",
    "NERExample",
    "QADataset",
    "QAExample",
    "RelationExtractionDataset",
    "RelationExtractionExample",
    "SummarizationDataset",
    "SummarizationExample",
    "bio_tags_to_spans",
    "entity_level_f1",
    "mean_rouge_l_f1",
    "qa_exact_match",
    "qa_scores",
    "qa_token_f1",
    "relation_macro_f1",
    "rouge_l_f1",
    "calibration_score",
    "expected_calibration_error",
    "lari_score",
    "FailureCategory",
    "FailureCode",
    "summarize_failure_codes",
]
